### ISSUE TITLE
Backslash does not work in double quote strings

### ISSUE THREAD

**Issue by jeffallen** [jschaf/bibtex#3]
If a URL has a literal tilde in it, it must be possible to escape that, instead of turning it into an NBSP.

Here's a unit test to show what I mean:

```diff
diff --git a/parser/parser_test.go b/parser/parser_test.go
index 0029289..474970c 100644
--- a/parser/parser_test.go
+++ b/parser/parser_test.go
@@ -209,6 +209,13 @@ func TestParseFile_BibDecl_ModeParseStrings(t *testing.T) {
 			asts.WithBibTags("howPublished",
 				asts.QuotedTextExpr(0, asts.Text(`\url`),
 					asts.BraceTextExpr(1, asts.Text("http://example.com/foo-bar/"), asts.NBSP(), asts.Text("baz/"))))},
+		{`@article{cite_key,
+		   howPublished = "\url{http://example.com/foo-bar/\~baz/}"
+		  }`,
+			asts.WithBibKeys("cite_key"),
+			asts.WithBibTags("howPublished",
+				asts.QuotedTextExpr(0, asts.Text(`\url`),
+					asts.BraceTextExpr(1, asts.Text("http://example.com/foo-bar/~baz/"))))},
 		{`@article { cite_key, title = {\href{https://nyt.com/}{Dollar \$140}} }`,
 			asts.WithBibKeys("cite_key"),
 			asts.WithBibTags("title",
```

**Comment by jschaf** [comment]
Should be fixed by https://github.com/jschaf/bibtex/commit/b3e70e2ff4816318a19eb5700c79be189dfb46d2. If not, let me know. The AST will produce a `CmdText` node with the proper string value.

A couple notes:

- I can't figure out how backslash in a `url` field or in a `\url` macro should work. It produces escaped text in biblatex which is probably not what you want.  Instead, the commit allows unescaped tildes which I believe is how most bib styles behave.

- I added limited Latex command parsing for `\url` and `\hyperref` so I've begun the descent into ~madness~ parsing latex. I figure I can special case enough latex macros to cover the vast majority of real-world bibtex files.
